### ISSUE TITLE
Compatibility issue with scikit-image==0.12.1

### ISSUE THREAD

**Issue by pfrwilson** [ChenjieXu/selective_search#6]
When I use selective-search==1.0.0 with scikit-image==0.12.1, I receive an error upon importing selective search. Selective search attempts to access the name grey2rgb from skimage.color, but in skimage 0.12.1 this name is gray2rgb (with an a). I was able to sucessfully use selective-search when I changed this grey to gray in the import statement.

**Comment by ChenjieXu** [comment]
Thanks for informing me. It is fixed in the lastest version. Have a good day.
